version: '3'

services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    expose: [9042]

  smudge:
    build: .
    container_name: smudge
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore:
            - .git
            - docker-compose.yml
    environment:
      REST_LISTENADDR: ":3000"
      GRPC_LISTENADDR: ":4000"
      SCYLLA_DB_CLUSTER: "scylla"
      SCYLLA_DB_KEYSPACE: "smudge"
    ports:
      - "3000:3000"
      - "4000:4000"
    links:
      - scylla
    depends_on:
      - scylla

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./scylla/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "cassandra://scylla/smudge", "up"]
    depends_on:
      - scylla
      - smudge
    links:
      - scylla
