// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type UserInput struct {
	Name string `json:"name"`
}
